<?php
$product = $block->getProduct();
$helper = $this->helper("Vnecoms\GrabPay\Helper\Data");
?>

<?php if($helper->isAllowPayLater()): ?>
<div class="grab-price-divider-widget"
     data-money-format="<?= $helper->getBaseCurrencyAmountGrabpay() ?>"
     data-product-price="<?= $helper->getProductPriceForGrabpay($product) ?>"
     data-min-price="<?= $helper->getMinTotal() ?>"
     data-max-price="<?= $helper->getMaxTotal() ?>"
     data-currency-code="<?= $helper->getBaseCurrencyGrabpay() ?>"
     data-widget-type="single_line"
     data-widget-size="small"
>
</div>

<script type="text/javascript">
    require(
        [
            'jquery',
            'Vnecoms_GrabPay/js/core/grab-paylater'
        ],
        function(
            $,
            GrabWidget
        ) {
            GrabWidget.invoke();
        }
    );
</script>
<?php endif; ?>